<?php
$users = new Users();
if ($users->count() > 0) {

}
?>
<!doctype html>
<html lang="en">
<body>
<form class="form-signin" method="post" action="main/index.phtml">
    <img class="mb-4" src="../public/img/teapot.jpg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit" > Sign in</button>
    <a href="/signup"> Зарегистрироваться </a>

    <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
</form>
</body>
</html>